import { Header } from '@/components/Header';
import './globals.css';
import { Karla, Bai_Jamjuree } from 'next/font/google';
import { ToastContainer } from 'react-toastify';
import {ToastProvider} from "@/shared/storage/Toast/ToastProvider";

const karla = Karla({
  subsets: ['latin'],
  variable: '--font-karla',
});

const BaiJamjuree = Bai_Jamjuree({
  subsets: ['latin'],
  weight: '700',
  variable: '--font-bai-jamjuree',
});

export const metadata = {
  title: 'Crystal',
  description: 'Generated by crystal',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {


  return (
    <html lang="en">
      <body
        className={`${BaiJamjuree.variable} ${karla.variable} min-h-screen bg-gray-900 text-gray-100`}
      >
        <div className="m-auto flex h-screen max-w-[1368px] flex-col gap-3 p-4 text-gray-200">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
